version: "2"
linters:
  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
          allow:
            - github.com/gorilla/securecookie
            - github.com/gorilla/sessions
            - github.com/valkey-io/valkey-go